### ISSUE TITLE
Help with getting started

### ISSUE THREAD

**Issue by marcohald** [dimagoltsman/generic-remote-control-card#14]
I have a problem with the Integration to Lovelace.
My Yaml looks like this
```
  - title: Soundbar
    path: soundbar
    badges: []
    cards: []
    resources:
      - url: /hacsfiles/generic-remote-control-card/generic-remote-control-card.js
        type: module
```
What do I need to do to see an example Remote ?
